import { StyleSheet } from 'react-native';

const page = '#f6f3ea';
const surface = '#ffffff';
const text = '#283618';
const muted = '#606c38';
const primary = '#606c38';
const accent = '#dda15e';
const danger = '#bc6c25';
const border = 'rgba(96, 108, 56, 0.18)';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: page,
  },
  scrollContent: {
    paddingBottom: 112,
  },
  hero: {
    height: 520,
    backgroundColor: '#0a1617',
  },
  heroImage: {
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  heroOverlay: {
    flex: 1,
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 34,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerButton: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.92)',
  },
  heroContent: {
    gap: 10,
  },
  heroBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  heroBadge: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
    backgroundColor: 'rgba(8,11,11,0.52)',
  },
  heroBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '900',
  },
  title: {
    color: '#fff',
    fontSize: 36,
    lineHeight: 40,
    fontWeight: '900',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  locationText: {
    flex: 1,
    color: '#e9f5ef',
    fontSize: 14,
    fontWeight: '800',
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 18,
    gap: 18,
  },
  engagementPanel: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 14,
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: border,
    backgroundColor: surface,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 3,
  },
  ratingBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  ratingValue: {
    color: text,
    fontSize: 24,
    lineHeight: 28,
    fontWeight: '900',
  },
  ratingLabel: {
    color: muted,
    fontSize: 12,
    fontWeight: '800',
  },
  priceBlock: {
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  priceLabel: {
    color: muted,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  priceValue: {
    color: danger,
    fontSize: 22,
    fontWeight: '900',
  },
  factGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  factItem: {
    flex: 1,
    minHeight: 110,
    gap: 7,
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: border,
    backgroundColor: '#fffdf8',
  },
  factLabel: {
    color: muted,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  factValue: {
    color: text,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '900',
  },
  section: {
    gap: 10,
  },
  sectionCard: {
    gap: 12,
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: border,
    backgroundColor: surface,
  },
  sectionKicker: {
    color: accent,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  sectionTitle: {
    color: text,
    fontSize: 25,
    lineHeight: 29,
    fontWeight: '900',
  },
  sectionTitleSmall: {
    color: text,
    fontSize: 19,
    fontWeight: '900',
  },
  description: {
    color: muted,
    fontSize: 14,
    lineHeight: 23,
    fontWeight: '600',
  },
  highlightItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 9,
  },
  highlightText: {
    flex: 1,
    color: text,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  itineraryList: {
    gap: 12,
  },
  itineraryItem: {
    flexDirection: 'row',
    gap: 12,
  },
  dayBadge: {
    width: 62,
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: primary,
  },
  dayBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '900',
  },
  itineraryContent: {
    flex: 1,
    gap: 4,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: border,
  },
  itineraryTitle: {
    color: text,
    fontSize: 15,
    fontWeight: '900',
  },
  itineraryDescription: {
    color: muted,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
  },
  serviceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  serviceItem: {
    width: '48%',
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(0, 180, 216, 0.08)',
  },
  serviceText: {
    flex: 1,
    color: text,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    minHeight: 88,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 18,
    borderTopWidth: 1,
    borderTopColor: border,
    backgroundColor: surface,
  },
  bottomLabel: {
    color: muted,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  bottomPrice: {
    color: text,
    fontSize: 21,
    fontWeight: '900',
  },
  bookButton: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 18,
    borderRadius: 8,
    backgroundColor: primary,
  },
  bookButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '900',
  },
  emptyPage: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    padding: 24,
    backgroundColor: page,
  },
  emptyTitle: {
    color: text,
    fontSize: 17,
    fontWeight: '900',
    textAlign: 'center',
  },
  emptyButton: {
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 18,
    borderRadius: 8,
    backgroundColor: primary,
  },
  emptyButtonText: {
    color: '#fff',
    fontWeight: '900',
  },
});
