import { StyleSheet } from 'react-native';

const page = '#f6f3ea';
const surface = '#ffffff';
const text = '#283618';
const muted = '#606c38';
const primary = '#606c38';
const accent = '#dda15e';
const border = 'rgba(96, 108, 56, 0.18)';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: page,
  },
  scrollContent: {
    paddingBottom: 34,
  },
  hero: {
    height: 430,
    justifyContent: 'flex-end',
    backgroundColor: '#0a1617',
  },
  heroImage: {
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  heroOverlay: {
    flex: 1,
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 58,
    paddingBottom: 34,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  heroTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brandText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '900',
  },
  heroBadge: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  heroBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '800',
  },
  heroCopy: {
    gap: 8,
  },
  greeting: {
    color: 'rgba(255,255,255,0.86)',
    fontSize: 15,
    fontWeight: '700',
  },
  subtitle: {
    color: '#fff',
    fontSize: 38,
    lineHeight: 42,
    fontWeight: '900',
  },
  heroDescription: {
    maxWidth: 330,
    color: 'rgba(255,255,255,0.86)',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '600',
  },
  searchPanel: {
    marginHorizontal: 16,
    marginTop: -34,
    padding: 12,
    borderRadius: 8,
    backgroundColor: surface,
    borderWidth: 1,
    borderColor: border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 5,
  },
  searchBar: {
    height: 48,
    borderRadius: 6,
    backgroundColor: '#f8f6ee',
    elevation: 0,
  },
  searchInput: {
    minHeight: 0,
    color: text,
    fontSize: 13,
  },
  quickBookingGrid: {
    marginTop: 12,
    gap: 10,
  },
  quickBookingItem: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: border,
    backgroundColor: '#fffdf8',
  },
  quickLabel: {
    color: muted,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  quickValue: {
    color: text,
    fontSize: 14,
    fontWeight: '900',
  },
  statsStrip: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 16,
    paddingTop: 18,
  },
  statItem: {
    flex: 1,
    minHeight: 74,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: border,
    backgroundColor: '#fffdf8',
  },
  statValue: {
    color: text,
    fontSize: 18,
    fontWeight: '900',
  },
  statLabel: {
    marginTop: 4,
    color: muted,
    fontSize: 10,
    fontWeight: '700',
    textAlign: 'center',
  },
  categoriesContainer: {
    paddingLeft: 16,
    paddingVertical: 16,
  },
  chip: {
    marginRight: 9,
    borderRadius: 999,
    backgroundColor: surface,
    borderWidth: 1,
    borderColor: border,
  },
  chipActive: {
    backgroundColor: primary,
    borderColor: primary,
  },
  chipText: {
    color: text,
    fontSize: 12,
    fontWeight: '800',
  },
  chipTextActive: {
    color: '#fff',
  },
  weatherPanel: {
    marginHorizontal: 16,
    marginBottom: 20,
    flexDirection: 'row',
    gap: 12,
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: border,
    backgroundColor: '#fffdf8',
  },
  weatherIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 180, 216, 0.12)',
  },
  weatherCopy: {
    flex: 1,
    gap: 4,
  },
  panelTitle: {
    color: text,
    fontSize: 15,
    fontWeight: '900',
  },
  panelText: {
    color: muted,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
  },
  sectionHeader: {
    paddingHorizontal: 16,
    marginTop: 6,
    marginBottom: 12,
  },
  sectionHeaderCompact: {
    paddingHorizontal: 16,
    marginTop: 4,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionHeaderInner: {
    marginBottom: 12,
  },
  sectionEyebrow: {
    color: accent,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  sectionTitle: {
    marginTop: 4,
    color: text,
    fontSize: 26,
    lineHeight: 30,
    fontWeight: '900',
  },
  sectionTitleSmall: {
    color: text,
    fontSize: 19,
    fontWeight: '900',
  },
  resultCount: {
    color: muted,
    fontSize: 12,
    fontWeight: '800',
  },
  destinationRail: {
    gap: 14,
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  destinationCard: {
    width: 210,
    height: 270,
    overflow: 'hidden',
    borderRadius: 8,
    backgroundColor: '#071b22',
  },
  destinationImage: {
    borderRadius: 8,
  },
  destinationOverlay: {
    flex: 1,
    justifyContent: 'space-between',
    padding: 14,
  },
  destinationRegion: {
    alignSelf: 'flex-start',
    minHeight: 32,
    paddingHorizontal: 12,
    paddingTop: 8,
    borderRadius: 999,
    overflow: 'hidden',
    color: '#fff',
    backgroundColor: 'rgba(8,35,48,0.5)',
    fontSize: 12,
    fontWeight: '900',
  },
  destinationName: {
    color: '#fff',
    fontSize: 26,
    fontWeight: '900',
  },
  destinationTours: {
    marginTop: 4,
    color: 'rgba(255,255,255,0.86)',
    fontSize: 13,
    fontWeight: '800',
  },
  featuredList: {
    paddingHorizontal: 16,
    gap: 16,
    marginBottom: 18,
  },
  tourList: {
    paddingHorizontal: 16,
    gap: 14,
  },
  featuredTourCard: {
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: surface,
  },
  tourCard: {
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: surface,
    borderWidth: 1,
    borderColor: border,
  },
  featuredTourImage: {
    width: '100%',
    height: 300,
  },
  cardImage: {
    width: '100%',
    height: 250,
  },
  cardImageRadius: {
    borderRadius: 8,
  },
  gradient: {
    flex: 1,
    justifyContent: 'space-between',
    padding: 14,
    borderRadius: 8,
  },
  cardTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  categoryBadge: {
    maxWidth: 126,
    minHeight: 32,
    justifyContent: 'center',
    paddingHorizontal: 11,
    borderRadius: 999,
    backgroundColor: 'rgba(8,11,11,0.58)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  categoryBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '900',
  },
  weatherBadge: {
    minHeight: 32,
    maxWidth: 148,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 224, 138, 0.92)',
  },
  weatherText: {
    color: text,
    fontWeight: '900',
    fontSize: 11,
  },
  tourInfo: {
    gap: 8,
  },
  tourTitle: {
    color: '#fff',
    fontSize: 25,
    lineHeight: 30,
    fontWeight: '900',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  locationText: {
    flex: 1,
    color: '#e9f5ef',
    fontSize: 13,
    fontWeight: '700',
  },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  metaPill: {
    minHeight: 28,
    paddingHorizontal: 9,
    paddingTop: 6,
    borderRadius: 999,
    overflow: 'hidden',
    color: '#fff',
    backgroundColor: 'rgba(255,255,255,0.16)',
    fontSize: 11,
    fontWeight: '800',
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    gap: 12,
  },
  priceLabel: {
    color: 'rgba(255,255,255,0.76)',
    fontSize: 11,
    fontWeight: '800',
  },
  priceText: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '900',
  },
  bookTextWrap: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 13,
    borderRadius: 6,
    backgroundColor: primary,
  },
  bookText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '900',
  },
  emptyState: {
    alignItems: 'center',
    gap: 10,
    marginHorizontal: 16,
    padding: 24,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: border,
    backgroundColor: '#fffdf8',
  },
  emptyTitle: {
    color: text,
    fontSize: 15,
    fontWeight: '900',
  },
  resetButton: {
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: 16,
    borderRadius: 6,
    backgroundColor: primary,
  },
  resetButtonText: {
    color: '#fff',
    fontWeight: '900',
  },
  servicesPanel: {
    marginHorizontal: 16,
    marginTop: 22,
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: border,
    backgroundColor: surface,
  },
  serviceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  serviceItem: {
    width: '48%',
    minHeight: 62,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(0, 180, 216, 0.08)',
  },
  serviceText: {
    flex: 1,
    color: text,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
  },
});
