import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  scrollContent: {
    paddingBottom: 40,
  },
  
  // Santorini Header Backdrop
  heroImageBackground: {
    width: '100%',
    height: 330,
  },
  heroGradient: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 44,
    justifyContent: 'space-between',
    paddingBottom: 36,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 48,
  },
  transparentButton: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
  },
  notificationContainer: {
    position: 'relative',
  },
  badge: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FF3B30',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },

  // Welcome / Title Section
  welcomeSection: {
    marginTop: 16,
    marginBottom: 10,
  },
  titleLine1: {
    fontSize: 34,
    fontWeight: '900',
    color: '#1E293B',
    lineHeight: 40,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 14,
    color: '#64748B',
    marginTop: 8,
    lineHeight: 20,
    fontWeight: '500',
  },

  // Floating Search Bar Overlay
  searchContainer: {
    paddingHorizontal: 20,
    marginTop: -28,
    marginBottom: 24,
    zIndex: 10,
  },
  searchBarWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    height: 56,
    paddingLeft: 18,
    paddingRight: 6,
    elevation: 5,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  searchIcon: {
    marginRight: 10,
  },
  searchPlaceholder: {
    flex: 1,
    fontSize: 15,
    color: '#94A3B8',
    fontWeight: '500',
  },
  searchButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FF5B22',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#FF5B22',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },

  // 4 Categories Row
  categoriesSection: {
    paddingHorizontal: 20,
    marginBottom: 28,
  },
  categoriesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  categoryItem: {
    alignItems: 'center',
    width: 76,
  },
  categoryIconCircle: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    elevation: 4,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    borderWidth: 1,
    borderColor: '#F8FAFC',
  },
  categoryText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#475569',
    textAlign: 'center',
  },

  // Universal Section Headers
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  sectionTitleWrap: {
    flex: 1,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.2,
  },
  viewAllText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FF5B22',
  },

  // Popular Destinations (Horizontal scroll)
  destinationsList: {
    paddingLeft: 20,
    paddingRight: 6,
  },
  destinationCard: {
    width: 124,
    height: 164,
    borderRadius: 18,
    marginRight: 14,
    overflow: 'hidden',
    backgroundColor: '#1E293B',
    elevation: 4,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  destinationImage: {
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  destGradient: {
    flex: 1,
    justifyContent: 'flex-end',
    padding: 12,
  },
  destName: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 18,
  },
  destCountry: {
    color: 'rgba(255, 255, 255, 0.75)',
    fontSize: 11,
    marginTop: 2,
    fontWeight: '600',
  },

  // Regional/Standard Tours List (Best Deals list)
  toursSection: {
    paddingHorizontal: 20,
  },
  tourList: {
    gap: 14,
  },
  tourCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 10,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    elevation: 3,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    alignItems: 'center',
  },
  tourImage: {
    width: 80,
    height: 80,
    borderRadius: 12,
  },
  tourDetails: {
    flex: 1,
    paddingLeft: 14,
    justifyContent: 'center',
  },
  tourTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1E293B',
    marginBottom: 4,
  },
  tourMeta: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '500',
  },
  tourRight: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    paddingRight: 4,
  },
  tourPrice: {
    fontSize: 16,
    fontWeight: '900',
    color: '#FF5B22',
  },
  tourBookBtn: {
    backgroundColor: '#FFF0EA',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    marginTop: 6,
  },
  tourBookBtnText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#FF5B22',
  },

  // Deal Badge styling inside card
  dealBadge: {
    backgroundColor: '#FF5B22',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    marginLeft: 10,
  },
  dealBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
  },

  // Empty State styling
  emptyState: {
    alignItems: 'center',
    gap: 12,
    marginHorizontal: 20,
    padding: 24,
    borderRadius: 16,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
  },
  emptyTitle: {
    color: '#1E293B',
    fontSize: 15,
    fontWeight: '700',
  },
  resetButton: {
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#FF5B22',
  },
  resetButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 13,
  },
  hotCard: {
    width: 180,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginRight: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#F1F5F9',
    elevation: 4,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  hotCardImage: {
    width: '100%',
    height: 110,
  },
  hotBadge: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: '#EF4444',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    gap: 4,
  },
  hotBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '900',
  },
  hotCardDetails: {
    padding: 10,
    flex: 1,
    justifyContent: 'space-between',
  },
  hotCardTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1E293B',
    lineHeight: 16,
  },
  hotCardBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 6,
  },
  hotCardPrice: {
    fontSize: 14,
    fontWeight: '900',
    color: '#FF5B22',
  },
  hotCardRating: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  hotCardRatingText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#475569',
  },
  saleBadge: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: '#EA580C',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  saleBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '900',
  },
  originalPriceText: {
    fontSize: 11,
    color: '#94A3B8',
    textDecorationLine: 'line-through',
  },
  purchasedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ECFDF5',
    borderColor: '#A7F3D0',
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    alignSelf: 'flex-start',
    marginTop: 4,
    gap: 4,
  },
  purchasedBadgeText: {
    color: '#059669',
    fontSize: 10,
    fontWeight: '800',
  },
  testimonialCard: {
    width: 280,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginRight: 14,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    elevation: 4,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  testimonialHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  testimonialAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    marginRight: 12,
  },
  testimonialName: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1E293B',
  },
  testimonialRole: {
    fontSize: 11,
    color: '#64748B',
    fontWeight: '600',
    marginTop: 2,
  },
  testimonialComment: {
    fontSize: 13,
    color: '#475569',
    lineHeight: 18,
    fontStyle: 'italic',
    fontWeight: '500',
  },
  testimonialStars: {
    flexDirection: 'row',
    marginTop: 4,
    gap: 2,
  },
});
