ALTER TABLE promotion_campaigns
    ADD COLUMN image_url TEXT NULL AFTER description,
    ADD COLUMN image_alt VARCHAR(180) NULL AFTER image_url,
    ADD COLUMN display_title VARCHAR(160) NULL AFTER image_alt,
    ADD COLUMN display_subtitle VARCHAR(255) NULL AFTER display_title,
    ADD COLUMN badge_text VARCHAR(80) NULL AFTER display_subtitle,
    ADD COLUMN cta_label VARCHAR(80) NULL AFTER badge_text,
    ADD COLUMN cta_url VARCHAR(255) NULL AFTER cta_label,
    ADD COLUMN sort_order INT NOT NULL DEFAULT 0 AFTER cta_url,
    ADD COLUMN is_featured BOOLEAN NOT NULL DEFAULT FALSE AFTER sort_order;

INSERT INTO promotion_campaigns (
    code,
    name,
    description,
    image_url,
    image_alt,
    display_title,
    display_subtitle,
    badge_text,
    cta_label,
    cta_url,
    sort_order,
    is_featured,
    start_at,
    end_at,
    target_member_level,
    conditions_json,
    reward_json,
    is_active
) VALUES
(
    'TEAMBUILDING_SUMMER_2026',
    'Du lich team building mua he 2026',
    'Goi uu dai cho doanh nghiep dat tour doan he, phu hop chuong trinh gan ket va gala dinner.',
    'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
    'Doan khach tham gia hoat dong team building ngoai troi',
    'Du lich - Teambuilding - Gala',
    'Chuong trinh he tron goi cho doanh nghiep tu 30 khach.',
    'Uu dai doanh nghiep',
    'Xem uu dai',
    '/promotions/TEAMBUILDING_SUMMER_2026',
    1,
    TRUE,
    CURRENT_TIMESTAMP,
    DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 90 DAY),
    'silver',
    JSON_OBJECT('minGuests', 30, 'applicableScope', 'corporate_group', 'advanceBookingDays', 14),
    JSON_OBJECT('type', 'percentage_discount', 'value', 12, 'maxDiscountAmount', 5000000),
    TRUE
),
(
    'COMPANY_TRIP_2026',
    'Ca cong ty cung di',
    'Khuyen mai tour doan lon cho cong ty to chuc du lich nghi duong, hoi nghi va gala cuoi nam.',
    'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80',
    'Nhom nhan vien cong ty cung tham gia chuyen di',
    'Ca cong ty cung di',
    'Goi tour tron goi cho doan 50 den 1000 khach.',
    'Tour doan lon',
    'Nhan tu van',
    '/promotions/COMPANY_TRIP_2026',
    2,
    TRUE,
    CURRENT_TIMESTAMP,
    DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 120 DAY),
    'gold',
    JSON_OBJECT('minGuests', 50, 'applicableScope', 'company_trip', 'includesGala', true),
    JSON_OBJECT('type', 'fixed_amount_discount', 'value', 3000000, 'gift', 'Free gala backdrop'),
    TRUE
),
(
    'FAMILY_CONNECT_2026',
    'Hanh trinh gan ket gia dinh',
    'Uu dai cho gia dinh va nhom ban dat tour nghi duong, mien phi tu van lich trinh rieng.',
    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    'Gia dinh nghi duong tren bai bien',
    'Hanh trinh gan ket',
    'Giam gia cho nhom gia dinh tu 6 khach tro len.',
    'Gia dinh',
    'Dat tour ngay',
    '/promotions/FAMILY_CONNECT_2026',
    3,
    TRUE,
    CURRENT_TIMESTAMP,
    DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 75 DAY),
    'bronze',
    JSON_OBJECT('minGuests', 6, 'applicableScope', 'family_group', 'advanceBookingDays', 7),
    JSON_OBJECT('type', 'cashback', 'value', 500000, 'voucherForNextTrip', true),
    TRUE
)
ON DUPLICATE KEY UPDATE
    description = VALUES(description),
    image_url = VALUES(image_url),
    image_alt = VALUES(image_alt),
    display_title = VALUES(display_title),
    display_subtitle = VALUES(display_subtitle),
    badge_text = VALUES(badge_text),
    cta_label = VALUES(cta_label),
    cta_url = VALUES(cta_url),
    sort_order = VALUES(sort_order),
    is_featured = VALUES(is_featured),
    start_at = VALUES(start_at),
    end_at = VALUES(end_at),
    target_member_level = VALUES(target_member_level),
    conditions_json = VALUES(conditions_json),
    reward_json = VALUES(reward_json),
    is_active = VALUES(is_active);
