/** Copy đồng bộ PromotionCommercePanel (web) — tiếng Việt có dấu */
export const commerceDeskCopy = {
  kicker: 'PROMOTION & COMMERCE',
  title: 'Điều phối voucher, campaign và gói bán kèm',
  subtitle:
    'Kiểm tra nhanh danh sách và bật/tắt trạng thái — cùng API với web backoffice.',
  tabVouchers: 'Vouchers',
  tabCampaigns: 'Campaigns',
  tabProducts: 'Products',
  tabCombos: 'Combos',
  summaryVouchers: (n: number) => `${n} vouchers`,
  summaryCampaigns: (n: number) => `${n} campaigns`,
  summaryProducts: (n: number) => `${n} products`,
  summaryCombos: (n: number) => `${n} combos`,
  searchPlaceholder: 'Tìm theo mã hoặc tên',
  reload: 'Tải lại',
  search: 'Tìm',
  loading: 'Đang tải dữ liệu...',
  empty: 'Không có dữ liệu phù hợp.',
  updatedProduct: 'Đã cập nhật sản phẩm.',
  updatedVoucher: 'Đã cập nhật voucher.',
  updatedCampaign: 'Đã cập nhật campaign.',
  updatedCombo: 'Đã cập nhật combo.',
  /** @deprecated use updatedProduct */
  updated: 'Đã cập nhật sản phẩm.',
  toggleOff: 'Tắt sản phẩm',
  toggleOn: 'Bật sản phẩm',
  toggleVoucherOff: 'Tắt voucher',
  toggleVoucherOn: 'Bật voucher',
  toggleCampaignOff: 'Tắt campaign',
  toggleCampaignOn: 'Bật campaign',
  toggleComboOff: 'Tắt combo',
  toggleComboOn: 'Bật combo',
  readOnlyProduct: 'Chỉ xem — không có quyền bật/tắt (voucher.delete)',
  readOnlyVoucher: 'Chỉ xem — không có quyền bật/tắt (voucher.publish)',
  readOnlyCampaign: 'Chỉ xem — không có quyền bật/tắt (promotion.campaign.publish)',
  readOnlyCombo: 'Chỉ xem — không có quyền bật/tắt (voucher.delete)',
  statusActive: 'Đang bật',
  statusInactive: 'Tạm tắt',
  price: 'Giá',
  stock: 'Tồn kho',
  gift: 'Quà tặng',
  giftYes: 'Có',
  giftNo: 'Không',
  voucherValue: 'Giá trị',
  voucherUsed: 'Đã dùng',
  voucherEnd: 'Kết thúc',
  campaignDisplay: 'Hiển thị',
  campaignStart: 'Bắt đầu',
  campaignEnd: 'Kết thúc',
  comboBase: 'Giá gốc',
  comboDiscount: 'Giảm',
  comboFinal: 'Giá bán',
  page: (current: number, total: number) => `Trang ${current}/${total}`,
  prev: 'Trước',
  next: 'Sau',
  screenTitle: 'Commerce Desk',
  noTabAccess: 'Không có quyền xem tab này.',
} as const;
