/** Nhãn đồng bộ với web PromotionCommercePanel (Commerce.api) */
export const productLabels = {
  screenList: 'Sản phẩm',
  screenDetail: 'Chi tiết sản phẩm',
  screenCreate: 'Thêm sản phẩm',
  screenEdit: 'Sửa sản phẩm',
  searchPlaceholder: 'Tìm theo tên hoặc SKU...',
  searchAction: 'Tìm',
  price: 'Giá',
  stock: 'Tồn kho',
  stockShort: 'SL',
  gift: 'Quà tặng',
  giftYes: 'Có',
  giftNo: 'Không',
  sku: 'SKU',
  name: 'Tên sản phẩm',
  description: 'Mô tả',
  type: 'Loại',
  status: 'Trạng thái',
  statusActive: 'Đang bật',
  statusInactive: 'Tạm tắt',
  id: 'Mã ID',
  sectionMore: 'Thông tin thêm',
  emptyTitle: 'Chưa có sản phẩm',
  emptySubtitle: 'Thêm sản phẩm đầu tiên để quản lý kho.',
  emptyCta: 'Thêm sản phẩm',
  errorTitle: 'Không tải được dữ liệu',
  retry: 'Thử lại',
  fabAdd: 'Thêm',
  edit: 'Chỉnh sửa',
  deactivate: 'Tắt sản phẩm',
  deactivateTitle: 'Tắt sản phẩm',
  deactivateMessage: (name: string) => `Bạn có chắc muốn tắt "${name}"? (giống thao tác trên web backoffice)`,
  cancel: 'Hủy',
  confirm: 'Xác nhận',
  save: 'Lưu thay đổi',
  create: 'Tạo sản phẩm',
  savedUpdate: 'Đã cập nhật sản phẩm',
  savedCreate: 'Đã tạo sản phẩm mới',
  deleted: 'Đã tắt sản phẩm',
  giftable: 'Có thể tặng quà',
  active: 'Đang hoạt động',
} as const;
